### ISSUE TITLE
Item 조회 METHOD 페이지네이션 기능 추가

### ISSUE THREAD

**Issue by fabius96** [Hanhae99-final-3team/final-be#18]
무한스크롤을 위한 페이지네이션 추가

- [x] 전체 상품 조회에 적용
- [x] 이중 카테고리 상품 조회에 적용
- [x] 펫 카테고리 상품 조회에 적용
- [x] 상품 카테고리 상품 조회에 적용

**Comment by HoisubLee** [comment]
저번주차 클론코딩 때 3조에서 구현한 내용 참고하시면 좋을 듯 합니다! (현중님 구현내용)
https://github.com/Hanhae99-clone-3team/wiselyClone_BE/commit/2d0308a00919305bc5b8279e82a0689ae1a10f72

-Controller 코드-
`@GetMapping("/items/detail/comments/{itemId}")
    public ResponseEntity<?> getReview(@PathVariable Long itemId, @PageableDefault Pageable pageable) {

        ReviewListResponseDto reviewGetResponseDtoList = reviewService.getReview(itemId, pageable);

        return ResponseEntity.ok(reviewGetResponseDtoList);
    }`

**Comment by HoisubLee** [comment]
-Controller 코드-
@GetMapping("/items/detail/comments/{itemId}")
    public ResponseEntity<?> getReview(@PathVariable Long itemId, @PageableDefault Pageable pageable) 
   {
        ReviewListResponseDto reviewGetResponseDtoList = reviewService.getReview(itemId, pageable);
        return ResponseEntity.ok(reviewGetResponseDtoList);
    }

**Comment by HoisubLee** [comment]
-Service 코드-
@Transactional(readOnly = true)
    public ReviewListResponseDto getReview(Long itemId, Pageable pageable) {
        Item item = itemRepository.findById(itemId).orElseThrow(
                () -> new IllegalArgumentException("Item이 존재하지 않습니다.")
        );

        Page<Review> reviewList =  reviewRepository.findAllByItem_Id(item.getId(),pageable);

        List<ReviewGetResponseDto> reviewGetResponseDtoList = new ArrayList<>();

        for (Review review : reviewList) {
            reviewGetResponseDtoList.add(
                    ReviewGetResponseDto.builder()
                            .commentId(review.getId())
                            .comment(review.getComment())
                            .name(review.getMember().getName())
                            .age((birthday(review.getMember().getBirthday()))+ "대")
                            .commentRate(review.getRate())
                            .createdAt(review.getCreatedAt())
                            .build()
            );
        }

        ReviewListResponseDto reviewListResponseDto = ReviewListResponseDto.builder()
                .itemId(itemId)
                .comments(reviewGetResponseDtoList)
                .build();

        return reviewListResponseDto;
    }

**Comment by HoisubLee** [comment]
-Repository 코드-
public interface ReviewRepository extends JpaRepository<Review, Long> 
{
    Page<Review> findAllByItem_Id(Long itemId, Pageable pageable);

    Review findReviewByItem_IdAndId(Long itemId, Long commentId);
}

**Comment by fabius96** [comment]
감사합니다! 좋은 참고가 되었습니다.
현재 기본적인 구현이 완료되었고 저녁식사 이후 FE분들과 협의하여 page의 size default 값을 설정하여 commit 및 PR 요청드리도록 하겠습니다.

**Comment by fabius96** [comment]
Pageable 부분 코드 수정 완료되었습니다.
PR은 isZzimed 기능 구현한다음에 요청하도록 하겠습니다.
