### ISSUE TITLE
[기능개발] Item CRUD 기능 구현

### ISSUE THREAD

**Issue by fabius96** [Hanhae99-final-3team/final-be#2]
- [x] 기초 CRUD 구현
- [x] 다중 이미지 업로드(S3) 구현
- [x] 카테고리에 따른 상품 조회 GET 요청 구현
- [x] Spring Security 활성화 및 Member class와의 연결을 통한 JWT 관련 로직 연결

**Comment by KORJaeyoungKim** [comment]
8/29 부터 본격적으로 시작 예정입니다.

**Comment by KORJaeyoungKim** [comment]
회원가입/로그인 부분과의 연결및 다중 이미지 업로드를 제외한 기본적인 CRUD는 구현 완료하였습니다.
8/30(화) 늦은 오후나 8/31(수) 오전 중으로 BE끼리 한 번 합치게되면 다시 한 번 업데이트 하겠습니다.

**Comment by KORJaeyoungKim** [comment]
다중 이미지 업로드 부분 추가 구현 시작하였습니다.

Controller 단에서 @ModelAttribute로 값을 받아오도록 변경하였더니 Response 값이 모두 Null이 뜨는 오류가 발생하여 원인을 찾아보았고, 기존 배웠던 @Setter 어노테이션을 붙여주는 방법이나 @AllArgumentConstructor 어노테이션을 붙여주는 방법을 시도해보았음에도 문제가 해결되지 않았으나 Request 요청을 하는 과정에서 JSON 타입이 아닌 FormData 타입으로 요청해야하는 부분을 잘못 설정해줘 발생한 오류로 확인되어 해결 완료하였습니다.

**Comment by KORJaeyoungKim** [comment]
이미지 업로드를 위해 S3uploader class를 생성하던 중 @Value 어노테이션이 인식되지 않는 오류가 발생하였으나 
import org.springframework.beans.factory.annotation.Value; 가 아닌
Lombok 어노테이션으로 잘 못 불러와 발생한 오류로 확인되어 해결 완료

추후 두 @Value 어노테이션 간 무슨 차이가 있는지 공부해볼 예정

**Comment by fabius96** [comment]
다중 이미지 업로드와 관련된 부분은 완료하였고 현재 GET 요청과 관련한 디테일한 부분에 대한 작업중에 있습니다.
전체 상품 조회 및 카테고리에 따른 게시글 조회 등을 작업중에 있습니다.

**Comment by fabius96** [comment]
카테고리에 따른 상품 조회 메소드 구현 완료하였습니다.
이제 item CRUD는 Member class와 연결만하면 됩니다.

**Comment by fabius96** [comment]
Member Class와 연결은 성공하였으나 수정METHOD에서 오류가 발생하여 수정하여야합니다.
(수정 시 이미지를 업로드하면 기존 게시글이 삭제되어버리는 현상)

**Comment by fabius96** [comment]
수정 시 발생하는 오류 해결 완료하였습니다.
트러블 슈팅 작성해놓도록 하겠습니다.
