### ISSUE TITLE
차트 API

### ISSUE THREAD

**Issue by crystal993** [Hanhae99-final-3team/final-be#46]
![image](https://user-images.githubusercontent.com/72599761/188568466-60e157ec-465d-483f-947f-ca209e57d4aa.png)

안녕하세요 재영님! 
아이템 카테고리별로 유저가 찜한 상품의 갯수를 보여주는 차트를 보여주는 데이터가 필요합니다!

```
const data = [
  {
    name: "사료",
    ZzimCnt: 6,
  },
  {
    name: "간식",
    ZzimCnt: 10,
  },
  {
    name: "의류",
    ZzimCnt: 12,
  },
  {
    name: "미용",
    ZzimCnt: 5,
  },
  {
    name: "장난감",
    ZzimCnt: 6,
  },
  {
    name: "기타용품",
    ZzimCnt: 8,
  },
];
```

그리고 아이템 카테고리별로 유저가 찜한 상품 뿐만 아니라 펫 카테고리별로 찜한 상품의 갯수를 보여주는 차트도 있으면 
좋을 것 같다는 생각이 들었는데, 혹시 어떠신가요??

**Comment by fabius96** [comment]
정리해서 요청해주셔서 감사합니다. 한 번 요청해주신 내용 바탕으로 API 우선 개발해보도록 하겠습니다.

**Comment by fabius96** [comment]
본격적인 개발에 앞서 해당 기능에 대해 좀 더 이야기를 나눠봤으면 합니다.
제가 자리로 찾아가도록 하겠습니다.

**Comment by fabius96** [comment]
수정님과의 논의를 바탕으로 해당 API를 다음과 같이 변경하기로 협의하였습니다.

data1 : 자기 등록 상품 가격의 총합
data 2 : 판매 완료된 자기등록상품 가격의 총합
data 3 : 내가 찜한 상품들의 가격 총합

위 데이터들을 각각 name(key01), price(key02) - List 형태로 보내주는 GET method를 개발하여야합니다.

**Comment by fabius96** [comment]
개발 완료하였습니다.
추후 PR 드리겠습니다.
