### ISSUE TITLE
쿠키가 String으로 쭉 저장되는 형태라 서버로 어떻게 보내드릴지 의논이 필요할 것 같습니다! 

### ISSUE THREAD

**Issue by crystal993** [Hanhae99-final-3team/final-be#79]
![image](https://user-images.githubusercontent.com/72599761/189947578-6f1f3f15-c7bc-45c1-b4a4-771cb26387db.png)

내가 방문한 페이지마다 쿠키가 스트링 형태로 쭉 저장이 되어서, 
어떻게 보내드려야 될지 감이 안 잡히네요 
하나씩 쪼개서 파싱해서 배열형태로 만들어서 보내드려야 될까요?? 

![image](https://user-images.githubusercontent.com/72599761/189948531-223c2e66-b6f5-4504-a90f-bd70ba78c692.png)
답변 주신대로 생각해봤는데 

header에 itemId=375, itemId=376

api.get(`/items/mypage/list`, {
      headers: {  itemId=375, itemId=376, ..... },
    }), 

이런 형태로 보낼 수는 있는데, headers 안에 너무 많은 데이터가 담기는 느낌이라 ㅜㅠ 😂
보시는대로 답변 부탁드립니다!

**Comment by fabius96** [comment]
넵 바로 자리로 찾아뵙도록 하겠습니다.

**Comment by fabius96** [comment]
우선은 String 형태로 헤더를 타고 전달받은 쿠키 데이터를 BE단 로직을 통해 해결하긴 하였습니다.
하지만 로직 자체가 깔끔하지 못하다고 판단되어 후에 리팩터링하면 좋을 듯 합니다.
내용은 금일중으로 PR 요청 드리겠습니다.
