### ISSUE TITLE
DB 상품 더미데이터 생성

### ISSUE THREAD

**Issue by fabius96** [Hanhae99-final-3team/final-be#82]
내일 오전 9시 기준으로 기존 DB데이터를 초기화할 예정입니다(Member Table 포함)

토요일 중간발표 시연을 위하여 새로운 더미데이터 제작이 필요하다고 판단됩니다.
사료 / 간식 / 장난감 / 의류 / 미용 / 기타 -  6개 아이템 카테고리 중
각자 1개씩 선택하셔서 20개씩 상품 더미데이터 등록 좀 부탁드리겠습니다.
(강아지, 고양이 각각 20개씩  -> 사료 카테고리 더미데이터 생성 시 강아지 - 사료 20개, 고양이 - 사료 20개)

진짜 서비스에 등록된 것과 같이 상품을 등록해주시길 부탁드리겠습니다.
감사합니다. 추가적으로 문의사항있으시면 언제든 말씀 부탁드리겠습니다.

**Comment by fabius96** [comment]
따로 중간발표 준비를 위해서 하셔야하는 것들이 있으신 것 같습니다.
더미데이터 작업은 금요일 자정까지만 좀 부탁드리겠습니다.

아래 체크리스트 첨부하오니 본인이 가져가실 카테고리 체크해주시고 코멘트 남겨주시길 부탁드리겠습니다.

**Comment by fabius96** [comment]
- [x] 사료
- [x] 간식
- [x] 장난감
- [x] 의류
- [ ] 미용
- [x] 기타

꼭 해당 상품 카테고리에 강아지, 고양이 카테고리 선택하셔서 각각 20개씩 등록 부탁드리겠습니다.

**Comment by fabius96** [comment]
제가 사료, 간식 2개 카테고리 진행하겠습니다.

**Comment by HoisubLee** [comment]
저는 의류 카테고리를 진행하겠습니다!

**Comment by crystal993** [comment]
저는 장난감 카테고리를 진행하겠습니다!

**Comment by 1argeD** [comment]
기타 태그 진행 중입니다
