### ISSUE TITLE
프로필 이미지 수정 기능 개발할까요?? 

### ISSUE THREAD

**Issue by crystal993** [Hanhae99-final-3team/final-be#89]
![image](https://user-images.githubusercontent.com/72599761/191522300-020c2dc6-d89d-4c56-8abd-890a223451a3.png)

와이어프레임을 보면 프로필 이미지 수정 기능이 있습니다 ㅎㅎ
이 부분이 있어야 완성도가 높은 사이트가 될 것 같긴 합니다! 

회섭님은 어떻게 생각하시는지 궁금합니다.

**Comment by HoisubLee** [comment]
저는 있으면 좋다고 생각합니다!
카카오 로그인 정보에도 프로필 이미지 받아올 수 있더라구요
그것도 활용해보면 좋을 것 같습니다!

**Comment by HoisubLee** [comment]
주형님과 상의하에 진행해보도록 하겠습니다!

**Comment by HoisubLee** [comment]
개발기간 부족으로 미완성된 기능입니다.
