### ISSUE TITLE
[기능개발] 거래완료버튼, 거래완료취소버튼 용 API 구현

### ISSUE THREAD

**Issue by fabius96** [Hanhae99-final-3team/final-be#9]
거래완료 및 거래완료취소 버튼을 위한 API를 구현할 필요가 있습니다.
추가로 item table 생성 시부터 해당 부분을 담당하는 필드를 추가하여야한다 판단됩니다.

**Comment by KORJaeyoungKim** [comment]
토큰 값과 관련된 로직 부분을 제외하고 구현 완료하였습니다.

**Comment by fabius96** [comment]
Member 클래스와의 연결을 통한 토큰 값 관련 로직 부분까지 구현 완료하였습니다.
